version: '3.1'
services:

  postgres:
    image: postgres:15
    restart: always
    container_name: postgres
    ports:
      - '6500:5432'
    volumes:
      - progresDB:/var/lib/postgresql/data
    env_file:
      - ./.env
    environment:
      - POSTGRES_HOST=${postgres_host}
      - POSTGRES_PORT=${postgres_port}
      - POSTGRES_USER=${postgres_user}
      - POSTGRES_PASSWORD=${postgres_password}
      - POSTGRES_DB=${postgres_db}

volumes:
  progresDB:

