version: '3.1'
services:

  postgres:
    image: postgres:15
    restart: always
    container_name: postgres
    ports:
      - '6500:5432'
    volumes:
      - progresDB:/var/lib/postgresql/data
    env_file:
      - ./.env

  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "8080:8080"

volumes:
  progresDB:

